[package]
name = "services"
version = "0.1.0"
edition = "2021"

[dependencies]
repositories = { path = "../repositories" }

derive_more = { version = "1.0.0", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
chrono = "0.4.38"
chrono-tz = "0.9.0"
utoipa = { version = "4.2.3", features = ["uuid", "chrono"] }
uuid = { version = "1.10.0", features = ["v4"] }
sea-orm = { version = "1.0.0", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
    "with-json",
] }
serde_with = "3.9.0"
slug = "0.1.6"
