[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
repositories = { path = "../repositories" }
services = { path = "../services" }

tokio = { version = "1.39.2", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
chrono = "0.4.38"
chrono-tz = "0.10.0"
config = "0.14.0"
derive_more = { version = "1.0.0", features = ["full"] }

# web
axum = "0.7.5"
tower-http = { version = "0.6.1", features = ["cors"] }
utoipa = { version = "4.2.3", features = ["axum_extras", "uuid", "chrono"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["axum"] }
utoipauto = "0.1.12"
clap = { version = "4.5.18", features = ["derive"] }

# logging
log = "0.4.22"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["registry", "json", "env-filter"] }
